version: '3.8'
services:
  generator-service:
    image: project-x/generator-service:local
    build:
      context: .
      dockerfile: ./generator-service/Dockerfile
    ports:
      - '8000:8000'
    environment:
      - JWT_SECRET=secret
    networks:
      - project-network

  front:
    image: project-x/front:local
    container_name: front
    build:
      context: .
      dockerfile: front/Dockerfile
      args:
        NEXT_PUBLIC_JWT_KEY: ${NEXT_PUBLIC_JWT_KEY}
    ports:
      - 3005:3005
    networks:
      - project-network

networks:
  project-network: {}
